### ISSUE TITLE
Remove direct dependencies on tidyverse

### ISSUE THREAD

**Issue by PKI-Kent** [PerkinElmer/phenoptr#6]
In [this article](https://www.tidyverse.org/articles/2018/06/tidyverse-not-for-packages/), Hadley Wickham requests / recommends that packages not depend directly on the `tidyverse` package.

I have mixed feelings about this; I want to encourage `phenoptr` users to use `tidyverse` and many of the `phenoptr` examples and vignettes do so.

**Comment by gadenbuie** [comment]
Thanks for this package! It makes working with inForm data much easier and I really appreciate how you've made sure the package works well within the tidyverse.

I think it's great to encourage use, but in terms of including `tidyverse` in the `Imports` section of your Description it may have undesirable downstream implications for users, and I think that if you're intending to send the package to CRAN at any point it also has upstream implications for the tidyverse team (because of CRAN's policy about reverse dependencies).

Personally, I think you make it clear in the README and the vignettes how to use the `phenoptr` with tidyverse packages, and I think it would be better to remove the meta-package from `phenoptr` Imports.

This does create a problem that packages used in the vignettes need to be listed in the Description, so you'd have to remove the `library(tidyverse)` calls. You can get around this by loading the required packages in a hidden chunk and then faking the `library(tidyverse)` call with an unevaluated R chunk.
